"use strict";
const {app}=require("@azure/functions");
const crypto=require("crypto");
const {SESSION_TTL_MINUTES,MAX_UPLOAD_BYTES,DEFAULT_RETURN_URL,json,preflight,storageSecret,saveSession,loadSession,deleteSession,signState,verifyState,validateReturnUrl,callbackUrl,safeName}=require("../storage/core");
const {isOAuth,oauthConfig,providerStatus,exchangeCode,authorizeUrl}=require("../storage/oauth");
const {uploadByProvider,validateCredentialConfig}=require("../storage/providers");
const PROVIDERS=["google-drive","onedrive","dropbox","box","ftp","sftp","webdav","s3"];
async function parseJson(request){try{return await request.json();}catch{return{};}}
app.http("easySaveProviders",{methods:["GET","OPTIONS"],authLevel:"anonymous",route:"easy-save/providers",handler:async request=>{if(request.method==="OPTIONS")return preflight(request);try{storageSecret();return json(request,200,{ok:true,providers:Object.fromEntries(PROVIDERS.map(p=>[p,providerStatus(p)])),maxUploadBytes:MAX_UPLOAD_BYTES});}catch(e){return json(request,503,{ok:false,error:e.message,providers:Object.fromEntries(PROVIDERS.map(p=>[p,providerStatus(p)]))});}}});
app.http("easySaveConnect",{methods:["POST","OPTIONS"],authLevel:"anonymous",route:"easy-save/connect/{provider}",handler:async request=>{if(request.method==="OPTIONS")return preflight(request);const provider=String(request.params.provider||"").toLowerCase();if(!PROVIDERS.includes(provider))return json(request,404,{error:"unsupported_provider"});const body=await parseJson(request),sessionId=String(body.sessionId||request.headers.get("x-easyfile-storage-session")||"");if(sessionId.length<16)return json(request,400,{error:"invalid_session"});try{if(isOAuth(provider)){const cfg=oauthConfig(provider);if(!cfg.configured)return json(request,503,{error:"provider_not_configured",provider});const returnUrl=validateReturnUrl(body.returnUrl),redirectUri=callbackUrl(request,provider),nonce=crypto.randomBytes(32).toString("base64url");await saveSession("__oauth-state",nonce,{provider,sessionId,returnUrl,redirectUri});const state=signState({nonce,exp:Date.now()+600000});return json(request,200,{provider,authorizeUrl:authorizeUrl(provider,redirectUri,state)});}const config=body.config||{};await validateCredentialConfig(provider,config);await saveSession(provider,sessionId,{provider,kind:"credentials",config});return json(request,200,{ok:true,provider,connected:true,expiresInMinutes:SESSION_TTL_MINUTES});}catch(e){return json(request,400,{error:String(e.message||e)});}}});
app.http("easySaveOauthCallback",{methods:["GET"],authLevel:"anonymous",route:"easy-save/oauth/callback/{provider}",handler:async request=>{const provider=String(request.params.provider||"").toLowerCase();let returnUrl=DEFAULT_RETURN_URL;try{const state=verifyState(request.query.get("state"));const pending=await loadSession("__oauth-state",state.nonce);await deleteSession("__oauth-state",state.nonce);if(pending.provider!==provider)throw new Error("oauth_provider_mismatch");returnUrl=validateReturnUrl(pending.returnUrl);const denied=request.query.get("error");if(denied)throw new Error(`oauth_denied:${denied}`);const code=request.query.get("code");if(!code)throw new Error("oauth_code_missing");const token=await exchangeCode(provider,code,pending.redirectUri);token.expiresAt=token.expires_in?Date.now()+Number(token.expires_in)*1000:0;await saveSession(provider,pending.sessionId,{provider,kind:"oauth",token});const target=new URL(returnUrl);target.searchParams.set("easySave","connected");target.searchParams.set("provider",provider);return{status:302,headers:{Location:target.toString(),"Cache-Control":"no-store","Referrer-Policy":"no-referrer"}};}catch(e){const target=new URL(returnUrl);target.searchParams.set("easySave","error");target.searchParams.set("provider",provider);target.searchParams.set("reason","connection_failed");return{status:302,headers:{Location:target.toString(),"Cache-Control":"no-store","Referrer-Policy":"no-referrer"}};}}});
app.http("easySaveUpload",{methods:["POST","OPTIONS"],authLevel:"anonymous",route:"easy-save/upload",handler:async request=>{if(request.method==="OPTIONS")return preflight(request);try{const form=await request.formData(),provider=String(form.get("provider")||"").toLowerCase(),remotePath=String(form.get("path")||""),file=form.get("file"),sessionId=String(request.headers.get("x-easyfile-storage-session")||form.get("sessionId")||"");if(!PROVIDERS.includes(provider))return json(request,400,{error:"unsupported_provider"});if(!file||typeof file.arrayBuffer!=="function")return json(request,400,{error:"file_required"});if(Number(file.size||0)>MAX_UPLOAD_BYTES)return json(request,413,{error:"file_too_large",maxUploadBytes:MAX_UPLOAD_BYTES});const connection=await loadSession(provider,sessionId),buffer=Buffer.from(await file.arrayBuffer()),result=await uploadByProvider(provider,{name:safeName(file.name),type:file.type,size:buffer.length,buffer},connection,remotePath);if(isOAuth(provider))await saveSession(provider,sessionId,connection);return json(request,200,{ok:true,provider,result});}catch(e){const message=String(e.message||e),status=/not_connected|expired|invalid_session/.test(message)?401:502;return json(request,status,{error:message.replace(/:[^:]+$/g,"")});}}});
app.http("easySaveDisconnect",{methods:["POST","OPTIONS"],authLevel:"anonymous",route:"easy-save/disconnect/{provider}",handler:async request=>{if(request.method==="OPTIONS")return preflight(request);const provider=String(request.params.provider||"").toLowerCase(),sessionId=String(request.headers.get("x-easyfile-storage-session")||"");if(!PROVIDERS.includes(provider))return json(request,404,{error:"unsupported_provider"});await deleteSession(provider,sessionId);return json(request,200,{ok:true,provider,connected:false});}});
