"use strict";
const OAUTH={
  "google-drive":{clientId:"EASYFILE_GOOGLE_CLIENT_ID",clientSecret:"EASYFILE_GOOGLE_CLIENT_SECRET",authorize:"https://accounts.google.com/o/oauth2/v2/auth",token:"https://oauth2.googleapis.com/token",scope:"https://www.googleapis.com/auth/drive.file"},
  onedrive:{clientId:"EASYFILE_MICROSOFT_CLIENT_ID",clientSecret:"EASYFILE_MICROSOFT_CLIENT_SECRET",authorize:"https://login.microsoftonline.com/common/oauth2/v2.0/authorize",token:"https://login.microsoftonline.com/common/oauth2/v2.0/token",scope:"offline_access Files.ReadWrite User.Read"},
  dropbox:{clientId:"EASYFILE_DROPBOX_CLIENT_ID",clientSecret:"EASYFILE_DROPBOX_CLIENT_SECRET",authorize:"https://www.dropbox.com/oauth2/authorize",token:"https://api.dropboxapi.com/oauth2/token",scope:"files.content.write files.content.read"},
  box:{clientId:"EASYFILE_BOX_CLIENT_ID",clientSecret:"EASYFILE_BOX_CLIENT_SECRET",authorize:"https://account.box.com/api/oauth2/authorize",token:"https://api.box.com/oauth2/token",scope:""}
};
function isOAuth(provider){return Boolean(OAUTH[provider]);}
function oauthConfig(provider){const cfg=OAUTH[provider];if(!cfg)return null;const clientId=process.env[cfg.clientId]||"",clientSecret=process.env[cfg.clientSecret]||"";return {...cfg,clientId,clientSecret,configured:Boolean(clientId&&clientSecret)};}
function providerStatus(provider){return isOAuth(provider)?{configured:oauthConfig(provider).configured,mode:"oauth"}:{configured:true,mode:"credentials"};}
async function tokenRequest(url,params,authHeader){const headers={"Content-Type":"application/x-www-form-urlencoded","Accept":"application/json"};if(authHeader)headers.Authorization=authHeader;const response=await fetch(url,{method:"POST",headers,body:new URLSearchParams(params)}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`oauth_token_exchange_failed:${response.status}:${data.error_description||data.error||"unknown"}`);return data;}
async function exchangeCode(provider,code,redirectUri){const cfg=oauthConfig(provider);if(!cfg?.configured)throw new Error("oauth_provider_not_configured");const base={code,grant_type:"authorization_code",redirect_uri:redirectUri};if(provider==="dropbox"){const auth=`Basic ${Buffer.from(`${cfg.clientId}:${cfg.clientSecret}`).toString("base64")}`;return tokenRequest(cfg.token,base,auth);}return tokenRequest(cfg.token,{...base,client_id:cfg.clientId,client_secret:cfg.clientSecret});}
async function refreshOAuth(provider,connection){const token=connection.token||{},expiresAt=Number(token.expiresAt||0);if(token.access_token&&(!expiresAt||expiresAt-Date.now()>120000))return connection;if(!token.refresh_token)return connection;const cfg=oauthConfig(provider);if(!cfg?.configured)throw new Error("oauth_provider_not_configured");let next;if(provider==="dropbox"){const auth=`Basic ${Buffer.from(`${cfg.clientId}:${cfg.clientSecret}`).toString("base64")}`;next=await tokenRequest(cfg.token,{grant_type:"refresh_token",refresh_token:token.refresh_token},auth);}else next=await tokenRequest(cfg.token,{grant_type:"refresh_token",refresh_token:token.refresh_token,client_id:cfg.clientId,client_secret:cfg.clientSecret});connection.token={...token,...next,refresh_token:next.refresh_token||token.refresh_token,expiresAt:next.expires_in?Date.now()+Number(next.expires_in)*1000:0};return connection;}
function authorizeUrl(provider,redirectUri,state){const cfg=oauthConfig(provider);if(!cfg?.configured)throw new Error("provider_not_configured");const params=new URLSearchParams({client_id:cfg.clientId,redirect_uri:redirectUri,response_type:"code",state});if(cfg.scope)params.set("scope",cfg.scope);if(provider==="google-drive"){params.set("access_type","offline");params.set("prompt","consent");}if(provider==="dropbox")params.set("token_access_type","offline");return `${cfg.authorize}?${params.toString()}`;}
module.exports={OAUTH,isOAuth,oauthConfig,providerStatus,exchangeCode,refreshOAuth,authorizeUrl};
